### ISSUE TITLE
Any channel group flags not implemented

### ISSUE THREAD

**Issue by LDY1997** [R1tschY/mdf4j#10]
I used examples.java to parse my MF4 file, and the result showed "Any channel group flags not implemented". How can I solve this problem？

**Comment by R1tschY** [comment]
Currently one simple signal data can be read. When one of the channel group flags are set, special handling is required, which is not implemented yet. In 5bb45d34a7fcfe868daa6d078cb56fe100d88362 the error message is improved, so the flags are given in the message. The only way to get the files parsed is than to implement the missing features ;)

**Comment by R1tschY** [comment]
Close because of inactivity
